### ISSUE TITLE
Custom form type validation does not show to the end-user

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#102]
I've created a custom form type "address" with some address fields of which some are required. I've placed this field on a specific address tab on the creation/edit form. But when you save the form when another tab is open, the validation triggers which is correct, but the user has no indication about what has happened until he opens the address tab itself.

Possible solution: Highlight tabs that have validation issues in them along with some kind of "Please fix the validation issues" message at the top of the form?

**Comment by NoUseFreak** [comment]
I agree, this should be more clear to the users. 
I think this feature worked at some time. At the time it switched to the tab. 
Showing a failure message at the top is also a good idea.
