### ISSUE TITLE
Entity form field required attribute is not respected by clientside validation

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#103]
I've created a form with an entity field that should be required. The HTML shows that it is recognised as being required, but the form still submits when no value is entered. Shouldn't clientside validation handle this?

https://www.dropbox.com/s/n1mksmuk0q5zuho/Screenshot%202015-09-22%2012.27.45.png?dl=0

**Comment by NoUseFreak** [comment]
I this this is because the html5 validation. I think this can be configured using an already present client side form validating library.

**Comment by NoUseFreak** [comment]
This seems to be an issue with the choice element. 

Hotfix:
```php
                'attr' => ['required' => 'required']
```

**Comment by NoUseFreak** [comment]
More info:
In standard sf this exists:

```twig
{%- block choice_widget_collapsed -%}
    {%- if required and placeholder is none and not placeholder_in_choices and not multiple -%}
        {% set required = false %}
    {%- endif -%}
//...
```

So adding a entity field should have a placeholder to be required.

```php
            ->add('test', 'choice', [
                'required' => true,
                'mapped' => false,
                'placeholder' => 'bla',
            ]);
```

**Comment by NoUseFreak** [comment]
@Ozmodiar  Can you confirm this works.

**Comment by Ozmodiar** [comment]
Yep, after adding a placeholder the required validation works as expected.

Closing the issue... Thanks!
