### ISSUE TITLE
Creating a new Text

### ISSUE THREAD

**Issue by peterroelants** [Clastic/Clastic#27]
Creating a new Text at /admin/text/edit gives the following error in de JavaScript console in chrome:  'An invalid form control with name='clastic_node[tabs][alias][alias]' is not focusable.'
No new Text seems te be created.

**Comment by NoUseFreak** [comment]
The problems exists in that Chrome tries to focus an element that is hidden.
In Firefox the HTML5 validation is show in the wrong place.

Implemtation of http://formvalidation.io/ might solve this issue.

**Comment by NoUseFreak** [comment]
Looks like formvalidation is not an option.

 - https://github.com/1000hz/bootstrap-validator
 - Self written.

**Comment by NoUseFreak** [comment]
@bdaenen Any suggestions?

**Comment by bdaenen** [comment]
https://github.com/guillaumepotier/Parsley.js/ looks more alive and used, has ie7+ support, allows for easy use through data attributes and allows for custom validators to be added. I've never used or tested it but it looks like a solod option to me.
