### ISSUE TITLE
[Alias] List should not show "Create your first"

### ISSUE THREAD

**Issue by NoUseFreak** [Clastic/Clastic#44]
Remove the link to create your first alias as we will not support extra aliases for now.

**Comment by NoUseFreak** [comment]
I would propose remove all notices and rely on the add button in the header.

**Comment by Ozmodiar** [comment]
It seems that this issue was already addressed by someone...

![screenshot 2015-10-27 00 14 40](https://cloud.githubusercontent.com/assets/512738/10745079/d8b914da-7c3e-11e5-96e4-bf4f4aad2e13.png)

So I guess this can be closed?
