### ISSUE TITLE
Expose node author/creation date/metadata information

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#52]
Edit form

**Comment by Ozmodiar** [comment]
I suppose there is some kind of autocomplete field needed for the author field? Any suggestions for this @NoUseFreak ?

**Comment by NoUseFreak** [comment]
You could use an entity field, as the user should exist. Select2 will then make it autocomplete.

**Comment by Ozmodiar** [comment]
Do you want the created date to be exposed in the node form?

**Comment by NoUseFreak** [comment]
Maybe show it as a disabled field.
