### ISSUE TITLE
"make" commands

### ISSUE THREAD

**Issue by denhul** [Clastic/Clastic#73]
help :)

**Comment by NoUseFreak** [comment]
Some projects add a `Makefile.bat` for Windows users. 
I prefer to promote the vagrant approach, but if you know how you may always supply one.

**Comment by denhul** [comment]
I'll look into it.. never used vagrant before, so I don't really know what to do with it

**Comment by NoUseFreak** [comment]
If you have [VirtualBox](https://www.virtualbox.org/) and [Vagrant](https://www.vagrantup.com/) installed, you can run `vagrant up` and you will have a pre-configured ubuntu made for Clastic development.

Than you can run `vagrant ssh` and `cd /vagrant && make build watch` to get up and running.

**Comment by Windmolders** [comment]
I made a bat file for windows users in a pullrequest, This doesn't use vagrant.
