### ISSUE TITLE
[StandardEdition] No layout on login screen

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#88]
It seems that the login screen does not load any styles...

How to reproduce? Logout and go back to the login form.

**Comment by NoUseFreak** [comment]
Added the missing SecurityBundle to the AppKernel.

To fix this without updating:

```php
$bundles = array(
    // ...
    new Clastic\SecurityBundle\ClasticSecurityBundle(),
);
```

**Comment by NoUseFreak** [comment]
You might need to clear your cache:

```bash
app/console cache:clear
```
