### ISSUE TITLE
Node title field

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#92]
The title field is always available when you are using a node module. But in some cases I want to change the label of the field to for example "name". Or remove the title field completely and fill it in the background using two other fields (firstname & lastname for example).

What is the best way achieve this? And is it even possible at this time?

**Comment by NoUseFreak** [comment]
It is possible by altering the form in the form extension. This is not my preferred way.
I wanted to get this done using translations. It should be possible to translate these the way the other translations are handled, but I can't get it to work.

**Comment by NoUseFreak** [comment]
Ok, translations is not the way to go. I would say just extend the form and alter the label. This way IF clastic will allow this, your change will not be broken.
